apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: pipeline-demo
  annotations:
    tektonci/build-namespace: pipeline-demo
  name: cloudland2023
  description: cloudLand2023
spec:
  type: service
  lifecycle: production
  owner: user:guest