apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cloudland2023
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-clone
  url: https://github.com/jquad-group/cloudland2023.git