apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  name: cloudland2023-pr
spec:
  source:
    kind: PullRequest
    name: cloudland2023
  pipelineRunSpec:
    pipelineRef:
      name: pullrequest-pipeline-go
    serviceAccountName: build-robot
    podTemplate:
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0    
    workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
          volumeMode: Filesystem
    params:
    - name: pathToContext
      value: /workspace/repo
    - name: commit
      value: ""
    - name: branch-name
      value: $.head.ref
    - name: repo-url
      value: git@github.com:jquad-group/cloudland2023.git
    - name: repo-url-alternate
      value: git@github.com:jquad-group/cloudland2023.git
    - name: gitrevision
      value: $.head.ref
    - name: owner
      value: jquad-group
    - name: repository
      value: cloudland2023
    - name: statusUrl
      value: $.statuses_url
    - name: state
      value: success
    - name: targetUrl
      value: http://localhost:9097/#/pipelineruns
    - name: context
      value: cloudland2023/tekton-ci    
    - name: githubSecretName
      value: git-clone
    - name: githubAccessTokenKey
      value: accessToken    