apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: test-application
spec:
  gitProvider:
    provider: Github
    secretRef: git-clone
    insecureSkipVerify: false
    github:
      url: https://github.com/jquad-group/test-application.git
      owner: jquad-group
      repository: test-application
  targetBranch: 
    name: refs/heads/main
  interval: 1m