apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: cloudland2023
spec:
  gitProvider:
    provider: Github
    secretRef: git-clone
    insecureSkipVerify: false
    github:
      url: https://github.com/jquad-group/cloudland2023.git
      owner: jquad-group
      repository: cloudland2023
  targetBranch: 
    name: refs/heads/main
  interval: 1m